# Generated by Django 4.1.1 on 2022-12-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_informepreparacion_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_guia', models.CharField(max_length=256)),
                ('remito', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='InformePreparacion',
        ),
    ]
