# Generated by Django 4.1.1 on 2022-11-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=25)),
                ('tarifa_por_dia', models.FloatField(null=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoMeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.BigIntegerField(default=0)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('banco', models.CharField(max_length=50)),
                ('cbu', models.CharField(max_length=22)),
                ('alias', models.CharField(max_length=50)),
                ('sucursal_por_defecto', models.CharField(max_length=50)),
                ('alta_por', models.CharField(max_length=50)),
                ('fecha_alta', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_trabajada', models.DateTimeField(null=True)),
                ('dni', models.IntegerField(null=0)),
                ('categoria', models.CharField(max_length=25)),
                ('tarifa', models.FloatField(null=0)),
                ('tipo_tarifa', models.CharField(max_length=10)),
                ('suma_a_tarifa', models.FloatField(null=0)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('total_dia', models.FloatField(null=0)),
                ('sucursal', models.CharField(max_length=50)),
                ('creado_por', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(null=True)),
                ('cbu', models.CharField(max_length=22)),
                ('alias', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
                ('editado', models.CharField(max_length=50)),
                ('fecha_de_edicion', models.DateTimeField(null=True)),
                ('pago_realizado', models.CharField(max_length=50)),
                ('fecha_pago', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('valor', models.FloatField(null=0)),
            ],
        ),
    ]
