# Generated by Django 4.1.1 on 2022-10-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=25)),
                ('tarifa_por_dia', models.FloatField(null=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoMeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(null=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_trabajada', models.DateTimeField(null=True)),
                ('dni', models.IntegerField(null=0)),
                ('cantidad', models.IntegerField(null=0)),
                ('categoria', models.CharField(max_length=25)),
                ('tarifa', models.FloatField(null=0)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
    ]
