# Generated by Django 4.1.1 on 2022-10-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=25)),
                ('tarifa_por_dia', models.FloatField(null=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_trabajada', models.DateTimeField(null=True)),
                ('dni', models.IntegerField(null=0)),
                ('categoria', models.CharField(max_length=25)),
                ('cantidad', models.IntegerField(null=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='empleadomeli',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='empleadomeli',
            name='fecha_trabajada',
        ),
        migrations.AlterField(
            model_name='empleadomeli',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleadomeli',
            name='dni',
            field=models.IntegerField(null=10),
        ),
        migrations.AlterField(
            model_name='empleadomeli',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
