# Generated by Django 4.1.1 on 2022-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_categoria_fichero_remove_empleadomeli_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichero',
            name='apellido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichero',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichero',
            name='tarifa',
            field=models.FloatField(default=1, null=0),
            preserve_default=False,
        ),
    ]
