# Generated by Django 4.1.1 on 2022-10-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_tipotarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichero',
            name='suma_a_tarifa',
            field=models.FloatField(default=25, null=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichero',
            name='tipo_tarifa',
            field=models.CharField(default=50, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichero',
            name='total_dia',
            field=models.FloatField(default=60, null=0),
            preserve_default=False,
        ),
    ]
