# Generated by Django 4.1.1 on 2022-10-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_fichero_suma_a_tarifa_fichero_tipo_tarifa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichero',
            name='cantidad',
        ),
    ]
