# Generated by Django 4.1.1 on 2022-10-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_remove_fichero_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadomeli',
            name='alias',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleadomeli',
            name='banco',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleadomeli',
            name='cbu',
            field=models.IntegerField(default=1, null=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleadomeli',
            name='sucursal_por_defecto',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichero',
            name='sucursal',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleadomeli',
            name='dni',
            field=models.IntegerField(default=1, null=0),
            preserve_default=False,
        ),
    ]
