# Generated by Django 4.1.1 on 2022-10-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadomeli',
            name='alta_por',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleadomeli',
            name='fecha_alta',
            field=models.DateTimeField(null=True),
        ),
    ]
