# Generated by Django 4.1.1 on 2022-10-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_empleadomeli_alta_por_empleadomeli_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichero',
            name='creado_por',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichero',
            name='fecha_creacion',
            field=models.DateTimeField(null=True),
        ),
    ]
