# Generated by Django 4.1.1 on 2022-10-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_fichero_creado_por_fichero_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='sucursal',
            field=models.CharField(max_length=30),
        ),
    ]
