# Generated by Django 4.1.1 on 2022-10-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_alter_sucursal_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichero',
            name='alias',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichero',
            name='cbu',
            field=models.CharField(default=1, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichero',
            name='editado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichero',
            name='fecha_de_edicion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fichero',
            name='fecha_pago',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fichero',
            name='pago_realizado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichero',
            name='responsable',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleadomeli',
            name='cbu',
            field=models.CharField(max_length=22),
        ),
    ]
