# Generated by Django 4.1.1 on 2022-10-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_alter_sucursal_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadomeli',
            name='cbu',
            field=models.BigIntegerField(default=0),
        ),
    ]
