# Generated by Django 4.1.1 on 2022-11-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0010_fichero_alias_fichero_cbu_fichero_editado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotarifa',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
