# Generated by Django 4.1.1 on 2022-10-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0010_fichero_alias_fichero_cbu_fichero_editado_and_more'),
        ('empleados', '0011_alter_empleadomeli_dni'),
    ]

    operations = [
    ]
