# Generated by Django 4.1.1 on 2022-11-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_alter_tipotarifa_tipo'),
        ('empleados', '0012_merge_20221021_1057'),
    ]

    operations = [
    ]
