# Generated by Django 4.1.1 on 2022-11-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('cliente', models.CharField(max_length=50)),
                ('sub_cliente', models.CharField(max_length=50)),
                ('unidades', models.IntegerField()),
                ('fecha_procesado', models.DateTimeField()),
                ('hora_procesado', models.CharField(max_length=8)),
                ('operario', models.CharField(max_length=20)),
                ('fecha_picking', models.DateTimeField()),
                ('fecha_armado', models.DateTimeField()),
                ('hora_inicio_picking', models.CharField(max_length=8)),
                ('hora_fin_picking', models.CharField(max_length=8)),
                ('hora_fin_armado', models.CharField(max_length=8)),
                ('estado_picking', models.CharField(max_length=20)),
                ('estado_armado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SectorDepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('cia_asociada', models.CharField(max_length=30)),
                ('razon_social', models.CharField(max_length=30)),
            ],
        ),
    ]
