# Generated by Django 4.1.1 on 2022-11-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_alter_globalpk_fecha_armado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpk',
            name='hora_fin_armado',
            field=models.CharField(max_length=8, null=0),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='hora_fin_picking',
            field=models.CharField(max_length=8, null=0),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='hora_inicio_picking',
            field=models.CharField(max_length=8, null=0),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='hora_procesado',
            field=models.CharField(max_length=8, null=0),
        ),
    ]
