# Generated by Django 4.1.1 on 2022-11-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_alter_globalpk_hora_fin_armado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpk',
            name='nombre_planilla',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
