# Generated by Django 4.1.1 on 2022-11-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0006_alter_pendientes_base_del_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientes',
            name='base_del_dia',
            field=models.IntegerField(null=0),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='finalizado',
            field=models.IntegerField(null=0),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='pend_dos',
            field=models.IntegerField(null=0),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='pend_tres_o_mas',
            field=models.IntegerField(null=0),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='pend_uno',
            field=models.IntegerField(null=0),
        ),
        migrations.AlterField(
            model_name='pendientes',
            name='pendiente_para_sig_dia',
            field=models.IntegerField(null=0),
        ),
    ]
