# Generated by Django 4.1.1 on 2022-12-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0008_pendientesarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subclientes',
            name='codigo',
            field=models.CharField(max_length=128),
        ),
    ]
