# Generated by Django 4.1.1 on 2023-01-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informes', '0009_alter_subclientes_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpk',
            name='iniciado_por',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
