# Generated by Django 4.1.1 on 2023-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0011_globalpk_hora_inicio_armado'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpk',
            name='fecha_inicio_picking',
            field=models.DateTimeField(null=True),
        ),
    ]
