# Generated by Django 4.1.1 on 2023-01-17 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('informes', '0012_globalpk_fecha_inicio_picking'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpk',
            name='creado_por',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalpk',
            name='fecha_finalizado_armado',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='globalpk',
            name='inicio_arm_por',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='iniciado_por',
            field=models.CharField(max_length=20),
        ),
    ]
