# Generated by Django 4.1.1 on 2023-01-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0013_globalpk_creado_por_globalpk_fecha_finalizado_armado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpk',
            name='finalizado_arm_por',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
