# Generated by Django 4.1.1 on 2023-01-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0014_globalpk_finalizado_arm_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpk',
            name='fecha_creacion',
            field=models.DateTimeField(null=True),
        ),
    ]
