# Generated by Django 4.1.1 on 2023-01-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0015_globalpk_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpk',
            name='en_picking',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
