# Generated by Django 4.1.1 on 2023-01-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0017_globalpk_en_armado'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpk',
            name='contribuyentes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
