# Generated by Django 4.1.1 on 2023-01-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0018_globalpk_contribuyentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpk',
            name='finalizado_pk_por',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalpk',
            name='usuario_inicio',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalpk',
            name='usuario_inicio_arm',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='creado_por',
            field=models.CharField(max_length=8, null=0),
        ),
    ]
