# Generated by Django 4.1.1 on 2023-01-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0020_alter_globalpk_contribuyentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpk',
            name='creado_por',
            field=models.CharField(max_length=128, null=0),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='hora_fin_armado',
            field=models.CharField(max_length=128, null=0),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='hora_fin_picking',
            field=models.CharField(max_length=128, null=0),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='hora_inicio_picking',
            field=models.CharField(max_length=128, null=0),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='hora_procesado',
            field=models.CharField(max_length=128, null=0),
        ),
    ]
