# Generated by Django 4.1.1 on 2023-01-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0021_alter_globalpk_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpk',
            name='en_armado',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='en_picking',
            field=models.CharField(max_length=128),
        ),
    ]
