# Generated by Django 4.1.1 on 2023-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0022_alter_globalpk_en_armado_alter_globalpk_en_picking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpk',
            name='fecha_armado',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='fecha_inicio_picking',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='fecha_picking',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='fecha_procesado',
            field=models.DateField(null=True),
        ),
    ]
