# Generated by Django 4.1.1 on 2023-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0023_alter_globalpk_fecha_armado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendientePkPorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('unidades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PenditenteArmPorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('unidades', models.IntegerField()),
            ],
        ),
    ]
