# Generated by Django 4.1.1 on 2023-01-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0024_pendientepkpordia_penditentearmpordia'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizadoArmPorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('unidades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FinalizadoPkPorDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('unidades', models.IntegerField()),
            ],
        ),
    ]
