# Generated by Django 4.1.1 on 2023-01-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0025_finalizadoarmpordia_finalizadopkpordia'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpk',
            name='cantidad_ediciones',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='globalpk',
            name='editado_por',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalpk',
            name='fecha_edicion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='globalpk',
            name='tipo',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
