# Generated by Django 4.1.1 on 2023-01-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0026_globalpk_cantidad_ediciones_globalpk_editado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpk',
            name='hora_procesado',
            field=models.TimeField(null=True),
        ),
    ]
