# Generated by Django 4.1.1 on 2023-02-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0028_alter_globalpk_hora_fin_armado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NombrePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='cliente',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='globalpk',
            name='sub_cliente',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
