# Generated by Django 4.1.1 on 2022-12-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_mensajeporestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailParaElBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
