# Generated by Django 4.1.1 on 2023-01-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_mailparaelbot'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMSJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=128)),
            ],
        ),
    ]
