# Generated by Django 4.1.1 on 2022-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='consecion',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
