# Generated by Django 4.1.1 on 2022-11-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catpicking',
            name='cia_asociada',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catrepo',
            name='cia_asociada',
            field=models.CharField(default='PHI', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catubicacion',
            name='cia_asociada',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
