# Generated by Django 4.1.1 on 2022-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='alto_cj',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='alto_un',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho_cj',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho_un',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo_cj',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo_un',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_cj',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_pall',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_un',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='vd',
            field=models.FloatField(null=0),
        ),
    ]
