# Generated by Django 4.1.1 on 2022-11-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_catpicking_cia_asociada_catrepo_cia_asociada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatUbicacionValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cia_asociada', models.CharField(max_length=3)),
                ('cod', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=180)),
            ],
        ),
    ]
