# Generated by Django 4.1.1 on 2022-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_producto_alto_cj_alter_producto_alto_un_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso_cj',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_pall',
            field=models.FloatField(),
        ),
    ]
