# Generated by Django 4.1.1 on 2022-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_rename_consecion_producto_concesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='concesion',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
