# Generated by Django 4.1.1 on 2022-10-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_alter_producto_peso_cj_alter_producto_peso_pall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=3)),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_cj',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso_pall',
            field=models.FloatField(null=0),
        ),
    ]
