# Generated by Django 4.1.1 on 2022-10-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_cia_alter_producto_peso_cj_alter_producto_peso_pall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='importado',
            new_name='importado_presis',
        ),
        migrations.AddField(
            model_name='producto',
            name='importado_saad',
            field=models.CharField(max_length=2, null='No'),
            preserve_default='No',
        ),
    ]
