# Generated by Django 4.1.1 on 2022-12-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_alter_producto_concesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cubicaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metro_cubico', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='concesion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
