# Generated by Django 4.1.1 on 2022-12-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_cubicaje_alter_producto_concesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='alto_pall',
            field=models.FloatField(null=1.4),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho_pall',
            field=models.FloatField(null=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo_pall',
            field=models.FloatField(null=1.2),
        ),
    ]
