# Generated by Django 4.1.1 on 2022-10-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_catpicking_catrepo_catubicacion_pack_tipoalm_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pack',
            new_name='TipoPack',
        ),
    ]
