# Generated by Django 4.1.1 on 2022-10-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_rename_pack_tipopack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipopack',
            old_name='descripcion',
            new_name='desc',
        ),
    ]
