# Generated by Django 4.1.1 on 2022-10-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_rename_descripcion_tipopack_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cia',
            name='descripcion',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='tipopack',
            name='desc',
            field=models.CharField(max_length=10),
        ),
    ]
