# Generated by Django 4.1.1 on 2022-10-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_alter_cia_descripcion_alter_tipopack_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipopack',
            old_name='desc',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='catpicking',
            name='descripcion',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='catrepo',
            name='descripcion',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='catubicacion',
            name='descripcion',
            field=models.CharField(max_length=180),
        ),
    ]
