# Generated by Django 4.1.1 on 2022-10-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='transportes',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='transportes',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='transportes',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='transportes',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='transportes',
            name='imagen5',
        ),
        migrations.RemoveField(
            model_name='transportes',
            name='imagen6',
        ),
        migrations.RemoveField(
            model_name='transportes',
            name='imagen7',
        ),
        migrations.AddField(
            model_name='transportes',
            name='dni',
            field=models.ImageField(default=1, null=0, upload_to=''),
            preserve_default=False,
        ),
    ]
